### PR TITLE
for transparent MacOS compilation and linking (10.12)

### PR DESCRIPTION
**Pull request by kirschen**

### CODE REVIEW

**Comment by andrey-popov** [comment]
Hi Henning,

These changes are probably fine (especially the missing `sstream` header), but I'm curious why you change the default extension for shared libraries on MacOS. Doesn't it work with `dylib`? Admittedly, I only built the package in Linux.

**Comment by kirschen** [comment]
Hi Andrey,
the .so suffix is primarily for simplicity when loading the library in root. I didn't even try to load the .dylib, but according to old ROOT-Forum threads ROOT didn't accept the .dylib extension (sym link would work) https://root-forum.cern.ch/t/loading-macos-dylibs-in-cint/11951/2

**Comment by andrey-popov** [comment]
Hi Henning,

Thanks for the link. I've tried building the project on MacOS and loading the constructed library in ROOT. Both
```C++
gSystem->Load("lib/libjecfit.dylib");
```
and
```C++
gSystem->Load("lib/libjecfit");
```
work for me (the command returns 0). I'm running with MacOS 10.13.2 and ROOT 6.12.04.

I would prefer to leave system-specific things for CMake to figure out and go with the default extension. By omitting the extension in the call to `TSystem::Load` you can also keep your code agnostic of the system. Could you please check that this works for you and, if it does, update the pull request removing the change to `CMakeLists.txt`? I will then merge the rest.

**Comment by kirschen** [comment]
with
`gSystem->Load("lib/libjecfit");`
working well, there is indeed no need for this. Pushed the changes.

**Comment by andrey-popov** [comment]
Thanks.

**Pull request merged**
